const types = {
  SET_START_UP_MODE: "SET_START_UP_MODE",
  SET_PREVIEW_MODE: "SET_PREVIEW_MODE",
  SET_RECORDING_MODE: "SET_RECORDING_MODE",
  SET_SESSION_PAUSE: "SET_SESSION_PAUSE",

  TOGGLE_TRAINING_SET: "TOGGLE_TRAINING_SET"
};

export default types;
