const types = {
  SET_START_UP_MODE: "SET_START_UP_MODE",
  SET_PREVIEW_MODE: "SET_PREVIEW_MODE",
  SET_RECORDING_MODE: "SET_RECORDING_MODE",
  SET_SESSION_PAUSE: "SET_SESSION_PAUSE",

  TRAINING_SET_TYPES: {
    TOGGLE_TRAINING_SET: "TOGGLE_TRAINING_SET",
    INITIALIZE_TRAINING_SET: "INITIALIZE_TRAINING_SET"
  },

  VIDEO_PLAYER_TYPES: {
    SET_VIDEO_PLAYER_STATE: "SET_VIDEO_PLAYER_STATE"
  },
  SONAR_TYPES: {
    SET_SONAR_STATE: "SET_SONAR_STATE"
  },
  MAP_TYPES: {
    SET_MAP_STATE: "SET_MAP_STATE",
    SET_MAP_VIEW_POSITION: "SET_MAP_VIEW_POSITION",
    SET_MAP_ZOOM_LEVEL: "SET_MAP_ZOOM_LEVEL"
  },
  CONTROL_MODE_TYPES: {
    CHANGE_CONTROL_MODE: "CHANGE_CONTROL_MODE"
  }
};

export default types;
